# 多周期Alpha策略默认配置文件

# 数据配置
data:
  data_source: "akshare"  # akshare, tushare, mock
  frequency: "1min"  # 1min, 5min, 15min, 30min, 1h, 1d
  universe: ["HS300", "ZZ500"]
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  benchmark: "000300.SH"
  
  # 真实数据源配置
  akshare:
    timeout: 30
    retry_times: 3
    retry_delay: 1
    cache_enabled: true
    cache_expire_hours: 24
    
  tushare:
    token: ""  # 请填入您的tushare token
    timeout: 30
    retry_times: 3
    cache_enabled: true
    
  # 分钟级数据特定配置
  minute_data:
    trading_sessions:
      morning: ["09:30", "11:30"]
      afternoon: ["13:00", "15:00"]
    exclude_weekends: true
    exclude_holidays: true
    fill_missing_method: "forward_fill"
    
  # 测试配置
  test:
    symbols: ["000001", "000002", "600000", "600036"]  # 测试股票代码
    test_days: 30  # 测试天数
    enable_simulation: true  # 是否启用分钟数据模拟

# 因子配置
factors:
  factor_groups: ["technical", "fundamental", "sentiment"]
  lookback_periods: [5, 10, 20, 60]
  factor_update_frequency: "1d"
  factor_neutralization: true
  factor_standardization: "zscore"

# 模型配置
models:
  model_types: ["lightgbm", "xgboost", "linear"]
  ensemble_method: "weighted_average"
  retrain_frequency: "1w"
  validation_method: "time_series_split"
  max_features: 50

# 组合配置
portfolio:
  optimization_method: "mean_variance"
  rebalance_frequency: "1d"
  max_position: 0.05
  max_turnover: 0.5
  transaction_cost: 0.001
  risk_budget: 0.15
  cycles: ["intraday", "daily", "weekly"]

# 风险配置
risk:
  max_drawdown: 0.1
  var_confidence: 0.95
  sector_exposure_limit: 0.3
  single_stock_limit: 0.05
  beta_range: [0.8, 1.2]

# 回测配置
backtest:
  initial_capital: 1000000
  benchmark: "000300.SH"
  transaction_cost: 0.001
  slippage: 0.0005

# 日志配置
logging:
  level: "INFO"
  file_path: "./logs/strategy.log"
  max_file_size: "10MB"
  backup_count: 5

# 监控配置
monitoring:
  alert_thresholds:
    max_drawdown: 0.08
    min_sharpe: 0.5
    max_volatility: 0.25
  notification:
    email: true
    sms: false
    webhook: false 